
# Local path to firmware images (no trailing slash).
# Even if you serve images from a remote machine, include 
# copies in a local directory. This enables iosfw to perform
# file size and hash integrity checks.
src_image_path: '../ios'

# Filesystem on device to store upgrade image.
dest_filesystem: 'flash:'

# Remote path on device. '/' means root filesystem (no trailing slash
# otherwise)
dest_image_path: '/'

# File transfer protocol
# Tested with ftp, tftp and scp.
transfer_proto: 'ftp'

# File transfer source machine
# Set 'localhost' to serve on local machine
# Currently supports only SCP from localhost.
transfer_source: ''

# File transfer username (FTP)
transfer_username: ''

# File transfer password (FTP)
transfer_password: ''

# Path that transfer_source serves images from.
# Include trailing slash. '/' means root filesystem.
transfer_path: '/'

# SSH config file to use in connections
ssh_config_file: '~/.ssh/config'

# Disable exec-timeout during upgrade operation
# If a copy or install operation takes longer than your line vty
# exec-timeout setting, the remaining operations will fail.
disable_exec_timeout: true

# Output / Logging
#
# How to notify you of progress.
# 
# tee: write progress info both to console (stdout) and log_file
# file: write progress info only to log_file
# console: write progress info only to console (stdout)
log_method: 'tee'
#
# File path for logging
log_file: 'iosfw.log'
# 
# Output verbosity level
# Acceptable values, from most verbose to least verbose:
#   - debug
#   - info
#   - warning
#   - error
#   - critical
file_log_level: debug
console_log_level: info

# Whether or not to enforce a feature set match between the running image
# and a prospective upgrade image.
#
# Example feature set strings: lanbase, ipbase, ipservices, universal
#
# NOTE: This failsafe ignores 'k9' (case insensitive) in the feature set
#       string. Example: the strings 'lanbase' and 'lanbasek9' are considered
#       equivalent.
#
# true:
#   - When searching for an upgrade image, the new image's feature set
#     string must match the prospective upgrade image's feature set string.
#     The device's model string must also appear in the list of models
#     associated with the image file, as configured in images.yaml.
#
# false:
#   - No feature set match is enforced. An upgrade image will match a device
#     solely based on the model string as configured in images.yaml.
match_feature_set: false

# Device reload
#
# If you do not want to schedule a reload, set either reload_in or reload_at
# to false.
#
# reload_in: Time delay before reloading device in HHH:MM or MMM
#   Examples:
#   - 1:30   one hour and thirty minutes from now
#   - 24:00  twenty-four hours from now (this time tomorrow)
#   - 240    two hundred and forty minutes from now
#   - 0      reload in 0 minutes (now)
#
# reload_at: Absolute time to schedule device reload in HH:MM 24-hour format.
#   If the time specified has already passed today, schedules for that time
#   tomorrow.
#   Examples:
#   - 00:00  (Default) Midnight tonight (technically 00:00 tomorrow morning)
#   - 04:30  4:30am
#   - 17:50  5:50pm
#
# NOTE: reload_in and reload_at are mutually exclusive (set one or the other).
#       If you specify both, you'll get an exception.
reload_in: false
reload_at: '00:00'

# Conditions under which to delete the current/running firmware image.
#
# never: Never delete old image.
#   - If dest_file_system has enough space for old and new images
#     to coexist, old image will remain after successful upgrade.
#   - If dest_file_system does NOT have enough space for old and new
#     images to coexist, upgrade will not proceed.
#
# always: Always delete old image.
#   - If dest_file_system has enough space for old and new images
#     to coexist, old image will be deleted after successful upgrade.
#   - If dest_file_system does NOT have enough space for old and new
#     images to coexist, old image will be deleted before copying new
#     image.
#
# as_needed: Only delete old image if insufficient space for both.
#   - If dest_file_system has enough space for old and new images
#     to coexist, leave both.
#   - If dest_file_system does NOT have enough space for old and new
#     images to coexist, old image will be deleted before copying new
#     image.
delete_running_image: 'as_needed'

# Conditions under which to delete old (not running) firmware images.
#
# never: Never delete old images.
#   - If dest_file_system has enough space for old and new images
#     to coexist, old image will remain after successful upgrade.
#   - If dest_file_system does NOT have enough space for old and new
#     images to coexist, upgrade will not proceed.
#
# always: Always delete old images.
#   - If dest_file_system has enough space for old and new images
#     to coexist, old image will be deleted after successful upgrade.
#   - If dest_file_system does NOT have enough space for old and new
#     images to coexist, old images will be deleted before copying new
#     image.
#
# as_needed: Only delete old images if insufficient space.
#   - If dest_file_system has enough space for old and new images
#     to coexist, leave both.
#   - If dest_file_system does NOT have enough space for old and new
#     images to coexist, old images will be deleted before copying new
#     image.
delete_old_images: 'always'

# If SCP is not enabled, run these config commands (in this order) to
# hopefully fix it.
fix_scp:
    - 'aaa authorization exec default local if-authenticated'
    - 'ip ssh version 2'
    - 'ip scp server enable'

# If NTP is not configured, run these commands (in this order) to
# hopefully fix it.
fix_ntp:
    - 'ntp authenticate'
    - 'ntp authentication-key 2007 md5 russislate'
    - 'ntp trusted-key 2007'
    - 'ntp server 10.250.20.1 key 2007'
    - 'clock timezone clock timezone PST -8'
    - 'clock summer-time PDT recurring 2 Sun Mar 2:00 1 Sun Nov 2:00'